### ISSUE TITLE
[BUG]Wifi Scan not working

### ISSUE THREAD

**Issue by Droopydroors** [CapibaraZero/fw#59]
Lilygo Embed CC1101 is not returning any wifi networks on scan

**To Reproduce**
Just scan networks and non show up

**Expected behavior**
To show at least 2.4g networks

**Comment by andreock** [comment]
Can you test this? On my Nano ESP32, this patch fixed the issue: 
[capibaraZero_0_5_2_lilygo_t_embed_cc1101.zip](https://github.com/user-attachments/files/18102471/capibaraZero_0_5_2_lilygo_t_embed_cc1101.zip)

**Comment by andreock** [comment]
Closed for inactivity. Probably fixed [here](https://github.com/CapibaraZero/fw/commit/32b3a856e622b406bf7cd7cc8ccd8276e2737588)
