### ISSUE TITLE
[BUG] on LilyGo T-Embed CC1101 RF capture makes the device freeze 

### ISSUE THREAD

**Issue by the-mentor** [CapibaraZero/fw#63]
When i try to capture RF using a LilyGo T-Embed CC1101 with version 0.5.1 the device freeze until i press the reset button

**Comment by andreock** [comment]
Fixed: https://github.com/CapibaraZero/fw/commit/37c0aea428bc3a3a1875e5c06cdb207103ac196f

You can test latest firmware(0.5.2) here: 
[capibaraZero_0_5_2_lilygo_t_embed_cc1101.zip](https://github.com/user-attachments/files/18223348/capibaraZero_0_5_2_lilygo_t_embed_cc1101.zip)
